name: 'Build and Scan MUSL Images'
description: 'Build and test from source in Docker container, then scan the image'
inputs:
  image-name:
    description: 'Docker image name'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  skip-dirs:
    description: 'Directories to skip during scanning'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Build and run in Docker container
      shell: bash
      run: |
        set -e
        IMAGE_NAME="${{ inputs.image-name }}"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
        docker build -t $IMAGE_NAME -f "${{ inputs.dockerfile }}" ./docker
        docker run --rm --mount type=bind,source="${GITHUB_WORKSPACE}",target=/project $IMAGE_NAME \
          /bin/sh -c 'git config --global --add safe.directory /project && dotnet test && ./build.sh'

    - name: Perform image scan
      uses: ./.github/actions/image_scan
      with:
        image-ref: ${{ inputs.image-name }}
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
        logout: 'true'
        skip-dirs: ${{ inputs.skip-dirs }}