<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.1.0</Version>
    <PackageId>AWS.OpenTelemetry.CloudWatchPluginOtel</PackageId>
    <Title>Amazon CloudWatch plugin for OpenTelemetry .NET</Title>
    <Description>Amazon CloudWatch plugin for OpenTelemetry .NET.</Description>
    <Authors>Amazon Web Services</Authors>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <TargetFrameworks Condition="$(OS) == 'Windows_NT'">$(TargetFrameworks);net472</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../../buildtools/awsoteldotnet.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnablePackageValidation>true</EnablePackageValidation>
    <OpenTelemetryVersion Condition="'$(OpenTelemetryVersion)' == ''">[1.15.3,2.0.0)</OpenTelemetryVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net472'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry" Version="$(OpenTelemetryVersion)" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <AdditionalFiles Include=".publicApi\PublicAPI.Shipped.txt" />
    <AdditionalFiles Include=".publicApi\PublicAPI.Unshipped.txt" />
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)../../stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(_IsPacking)' == 'true' ">
    <IsPackable>true</IsPackable>
    <PackageProjectUrl>https://github.com/aws-observability/aws-otel-dotnet-instrumentation/</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>See CHANGELOG.md in the project repository.</PackageReleaseNotes>
    <PackageTags>OpenTelemetry;OTEL;CloudWatch;tracing;metrics;AWS</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/aws-observability/aws-otel-dotnet-instrumentation.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup Condition=" '$(_IsPacking)' == 'true' ">
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="CHANGELOG.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
