name: 'Build and Scan Docker Image'
description: 'Build Docker image from distribution and scan for vulnerabilities'
inputs:
  image-name:
    description: 'Docker image name'
    required: true
  zip-path:
    description: 'Path to distribution zip file'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  platform:
    description: 'Platform (linux or windows)'
    required: true
    default: 'linux'

runs:
  using: 'composite'
  steps:
    - name: Prepare Linux distribution
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        set -e
        rm -rf ./OpenTelemetryDistribution
        mkdir -p ./OpenTelemetryDistribution
        unzip -o ${{ inputs.zip-path }} -d ./OpenTelemetryDistribution
        cp THIRD-PARTY-LICENSES ./OpenTelemetryDistribution/THIRD-PARTY-LICENSES
        echo "IMAGE_NAME=${{ inputs.image-name }}" >> $GITHUB_ENV

    - name: Prepare Windows distribution
      if: inputs.platform == 'windows'
      shell: powershell
      run: |
        Expand-Archive -LiteralPath ${{ inputs.zip-path }} -DestinationPath .\OpenTelemetryDistribution -Force
        $IMAGE_NAME="${{ inputs.image-name }}"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $env:GITHUB_ENV

    - name: Build Docker image
      shell: bash
      run: |
        set -e
        docker build -t ${{ inputs.image-name }} -f ${{ inputs.dockerfile }} .

    - name: Scan Docker image
      uses: ./.github/actions/image_scan
      with:
        image-ref: ${{ inputs.image-name }}
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
        logout: 'false'