receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  awsapplicationsignals:
    resolvers:
      - name: ""
        platform: ec2
  resourcedetection:
    detectors: [eks, env, ec2]
    timeout: 2s
    override: false

exporters:
  logging:
    verbosity: detailed
  awsxray:
    region: us-west-2
  awsemf:
    region: us-west-2
    log_group_name: "/aws/application-signals/data"
    namespace: "ApplicationSignals"
    dimension_rollup_option: "NoDimensionRollup"
    metric_declarations:
      - dimensions:
          - [Environment, Service, Operation]
          - [Environment, Service]
        label_matchers:
          - label_names:
              - Telemetry.Source
            regex: '^(ServerSpan|LocalRootSpan)$'
        metric_name_selectors:
          - Latency
          - Fault
          - Error
      - dimensions:
          - [Environment, Service, Operation, RemoteService, RemoteOperation, RemoteResourceIdentifier, RemoteResourceType]
          - [Environment, Service, Operation, RemoteService, RemoteOperation]
          - [Environment, Service, RemoteService]
          - [Environment, Service, RemoteService, RemoteOperation, RemoteResourceIdentifier, RemoteResourceType]
          - [Environment, Service, RemoteService, RemoteOperation]
          - [Environment, Service, RemoteService, RemoteResourceIdentifier, RemoteResourceType]
          - [RemoteService, RemoteResourceIdentifier, RemoteResourceType]
          - [RemoteService]
        label_matchers:
          - label_names:
              - Telemetry.Source
            regex: '^(ClientSpan|ProducerSpan|ConsumerSpan)$'
        metric_name_selectors:
          - Latency
          - Fault
          - Error


service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - awsxray
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
        - awsemf
