version: "3.7"
services:
  awscollector:
    image: amazon/aws-otel-collector
    command: ["--config=/otel-config.yaml"]
    volumes:
      - ./collector.yaml:/otel-config.yaml
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=


    ports:
     - '4316:4316'
     - '2000:2000'
     - '13133:13133'

  app:
    image: aspnetapp:latest
    environment: 
      - AWS_REGION=us-west-2
      - INSTANCE_ID
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://awscollector:4316 # TODO: workaround for trace exporter endpoint
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://awscollector:4316/v1/traces
      - OTEL_AWS_APPLICATION_SIGNALS_EXPORTER_ENDPOINT=http://awscollector:4316/v1/metrics
      - ASPNETCORE_URLS=http://+:8080
      - OTEL_METRICS_EXPORTER=none
      - OTEL_AWS_APPLICATION_SIGNALS_ENABLED=true
      - OTEL_TRACES_SAMPLER=xray
      - OTEL_TRACES_SAMPLER_ARG=endpoint=http://awscollector:2000,polling_interval=1
      - OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED=true
      - RESOURCE_DETECTORS_ENABLED=false
    ports:
      - '8080:8080'     
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./logs:/var/log/opentelemetry/dotnet
