version: "3.7"
services:
  otel:
    image: amazon/aws-otel-collector
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./collector-config-local.yml:/etc/otel-config.yaml
    ports:
      - '4318:4318'

  app:
    image: aspnetapp:latest
    environment: 
      - AWS_REGION=us-west-2
      - INSTANCE_ID
      - LISTEN_ADDRESS=0.0.0.0:8080
      - OTEL_RESOURCE_ATTRIBUTES=service.name=aws-otel-integ-test
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel:4318
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel:4318/v1/traces
      - OTEL_AWS_APPLICATION_SIGNALS_EXPORTER_ENDPOINT=http://otel:4318/v1/metrics
      - ASPNETCORE_URLS=http://+:8080
      - OTEL_METRICS_EXPORTER=none
      - OTEL_AWS_APPLICATION_SIGNALS_ENABLED=true
      - RESOURCE_DETECTORS_ENABLED=false
    ports:
      - '8080:8080'
