name: Daily scan

on:
  schedule: # scheduled to run at 14:00, 20:00, 02:00 UTC every day
    - cron: '0 14 * * *' # 6:00/7:00   PST/PDT (14:00 UTC)
    - cron: '0 20 * * *' # 12:00/13:00 PST/PDT (20:00 UTC)
    - cron: '0 02 * * *' # 18:00/19:00 PST/PDT (02:00 UTC)  
  workflow_dispatch: # be able to run the workflow on demand

env:
  AWS_DEFAULT_REGION: us-east-1

permissions:
  contents: read
  id-token: write

jobs:
  scan_and_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo for dependency scan
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d #v5.0.0
        with:
          dotnet-version: '8.0.x'

      - name: Install java for dependency scan
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 #v5.0.0
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Configure AWS credentials for dependency scan
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 #v5.0.0
        with:
          role-to-assume: ${{ secrets.SECRET_MANAGER_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Get NVD API key for dependency scan
        uses: aws-actions/aws-secretsmanager-get-secrets@a9a7eb4e2f2871d30dc5b892576fde60a2ecc802 #v2.0.10
        id: nvd_api_key
        with:
          secret-ids: ${{ secrets.NVD_API_KEY_SECRET_ARN }}
          parse-json-secrets: true

      # See http://jeremylong.github.io/DependencyCheck/dependency-check-cli/ for installation explanation
      - name: Install and run dependency scan
        id: dep_scan
        if: always()
        run: |
          gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 259A55407DD6C00299E6607EFFDE55BE73A2D1ED
          VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt | head -n1 | cut -d' ' -f1)
          curl -Ls "https://github.com/dependency-check/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
          curl -Ls "https://github.com/dependency-check/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip.asc" --output dependency-check.zip.asc
          gpg --verify dependency-check.zip.asc
          unzip dependency-check.zip
          
      - name: Run Dependency Check
        run: |
          ./dependency-check/bin/dependency-check.sh --project "AWS.Distro.OpenTelemetry.AutoInstrumentation" --nvdApiKey ${{ env.NVD_API_KEY_NVD_API_KEY }} --out . --scan "**/*.csproj"

      - name: Print dependency scan results on failure
        if: ${{ steps.dep_scan.outcome != 'success' }}
        run: less dependency-check-report.html

      - name: Configure AWS credentials for image scan
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 #v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Login to Public ECR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 #v3.5.0
        with:
          registry: public.ecr.aws
          
      - name: Perform high image scan
        if: always()
        id: high_scan
        uses: ./.github/actions/image_scan
        with:
          image-ref: "public.ecr.aws/aws-observability/adot-autoinstrumentation-dotnet:v1.9.1"
          severity: 'CRITICAL,HIGH'
          logout: 'false'

      - name: Perform low image scan
        if: always()
        id: low_scan
        uses: ./.github/actions/image_scan
        with:
          image-ref: "public.ecr.aws/aws-observability/adot-autoinstrumentation-dotnet:v1.9.1"
          severity: 'MEDIUM,LOW,UNKNOWN'
          logout: 'false'

      - name: Configure AWS Credentials for emitting metrics
        if: always()
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 #v5.0.0
        with:
          role-to-assume: ${{ secrets.MONITORING_ROLE_ARN }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Publish high scan status
        if: always()
        run: |
          value="${{ steps.high_scan.outcome == 'success' && '1.0' || '0.0' }}"
          aws cloudwatch put-metric-data --namespace 'ADOT/GitHubActions' \
            --metric-name Success \
            --dimensions repository=${{ github.repository }},branch=${{ github.ref_name }},workflow=daily_scan_high \
            --value $value

      - name: Publish low scan status
        if: always()
        run: |
          value="${{ steps.low_scan.outcome == 'success' && steps.dep_scan.outcome == 'success' && '1.0' || '0.0'}}"
          aws cloudwatch put-metric-data --namespace 'ADOT/GitHubActions' \
            --metric-name Success \
            --dimensions repository=${{ github.repository }},branch=${{ github.ref_name }},workflow=daily_scan_low \
            --value $value
