name: DotNet Instrumentation PR Build
on:
  pull_request:
    branches:
      - main
      - "release/v*"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build on Linux
        if: runner.os == 'Linux'
        run: bash build.sh

      - name: Build on Windows
        if: runner.os == 'Windows'
        run: .\build.cmd

      - name: Build on macOS
        if: runner.os == 'macOS'
        run: bash build.sh

      - name: Test on Linux
        if: runner.os == 'Linux'
        run: dotnet test

      - name: Test on Windows
        if: runner.os == 'Windows'
        run: dotnet test

      - name: Test on macOS
        if: runner.os == 'macOS'
        run: dotnet test

      - name: Build and scan x64 Linux image
        if: runner.os == 'Linux'
        uses: ./.github/actions/build-and-scan-images
        with:
          image-name: "pr-build-x64-glibc:latest"
          zip-path: "bin/aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip"
          dockerfile: "./Dockerfile.linux"
          platform: "linux"

      - name: Build and scan Windows image
        if: runner.os == 'Windows'
        uses: ./.github/actions/build-and-scan-images
        with:
          image-name: "pr-build-windows-2022:latest"
          zip-path: "./bin/aws-distro-opentelemetry-dotnet-instrumentation-windows.zip"
          dockerfile: "./Dockerfile.windows2022"
          platform: "windows"

  build-arm:
    runs-on: codebuild-adot-dotnet-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build on Linux
        run: bash build.sh

      - name: Test on Linux
        run: dotnet test

      - name: Build and scan Linux image
        uses: ./.github/actions/build-and-scan-images
        with:
          image-name: "pr-build-arm64-glibc:latest"
          zip-path: "bin/aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-arm64.zip"
          dockerfile: "./Dockerfile.linux"
          platform: "linux"

  build-x64-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Build in Docker container and scan
        uses: ./.github/actions/build-and-scan-images
        with:
          image-name: "pr-build-x64-musl:latest"
          dockerfile: "./docker/alpine.dockerfile"
          skip-dirs: '/usr/share/dotnet,/usr/share/powershell'
  
  build-arm-musl:
    runs-on: codebuild-adot-dotnet-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - name: Build in Docker container and scan
        uses: ./.github/actions/build-and-scan-images
        with:
          image-name: "pr-build-arm64-musl"
          dockerfile: "./docker/alpine.dockerfile"
          skip-dirs: '/usr/share/dotnet,/usr/share/powershell'

  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up and run contract tests with pytest
        run: |
          cd test
          bash ./build-and-install-distro.sh
          bash ./set-up-contract-tests.sh
          pytest contract-tests/tests