name: Release Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to tag the release with, e.g., 1.2.0
        required: true

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_PUBLIC_ECR_REGION: us-east-1
  AWS_PRIVATE_ECR_REGION: us-west-2
  AWS_SIGNING_KEY_REGION: us-west-2
  RELEASE_PUBLIC_REPOSITORY: public.ecr.aws/aws-observability/adot-autoinstrumentation-dotnet
  RELEASE_PRIVATE_REPOSITORY: 020628701572.dkr.ecr.us-west-2.amazonaws.com/adot-autoinstrumentation-dotnet
  RELEASE_PRIVATE_REGISTRY: 020628701572.dkr.ecr.us-west-2.amazonaws.com
  RELEASE_PRIVATE_S3: s3://adot-autoinstrumentation-dotnet-staging

permissions:
  id-token: write
  contents: write

jobs:
  release-multi-platform-image:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials for private ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_ECR_RELEASE }}
          aws-region: ${{ env.AWS_PRIVATE_ECR_REGION }}

      - name: Log in to AWS private ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.RELEASE_PRIVATE_REGISTRY }}

      - name: Configure AWS credentials for public ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_ECR_RELEASE }}
          aws-region: ${{ env.AWS_PUBLIC_ECR_REGION }}

      - name: Log in to AWS public ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws

      - name: Create multi-platform image and push to Amazon public ECR
        run: |
          docker manifest create ${{ env.RELEASE_PUBLIC_REPOSITORY }}:v${{ github.event.inputs.version }} ${{ env.RELEASE_PUBLIC_REPOSITORY }}:v${{ github.event.inputs.version }}-amd64 ${{ env.RELEASE_PUBLIC_REPOSITORY }}:v${{ github.event.inputs.version }}-arm64 ${{ env.RELEASE_PUBLIC_REPOSITORY }}:v${{ github.event.inputs.version }}-windows2019 ${{ env.RELEASE_PUBLIC_REPOSITORY }}:v${{ github.event.inputs.version }}-windows2022
          docker manifest inspect ${{ env.RELEASE_PUBLIC_REPOSITORY }}:v${{ github.event.inputs.version }}
          docker manifest push ${{ env.RELEASE_PUBLIC_REPOSITORY }}:v${{ github.event.inputs.version }}

  build-release-nuget:
    runs-on: windows-latest

    strategy:
        fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore .\src\AWS.Distro.OpenTelemetry.AutoInstrumentation /p:_IsPacking=true

      - name: Build solution
        run: >
          dotnet build .\src\AWS.Distro.OpenTelemetry.AutoInstrumentation
          /p:Configuration=Release
          --no-restore
      - name: Assume signer role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ARTIFACT_ACCESS_ROLE_ARN }}
          aws-region: ${{ env.AWS_SIGNING_KEY_REGION }}

      - name: Invoke Signing script
        env:
          UNSIGNED_BUCKET: ${{ secrets.AWS_UNSIGNED_BUCKET_NAME }}
          SIGNED_BUCKET: ${{ secrets.AWS_SIGNED_BUCKET_NAME }}
        #TODO: There is probably a better way to pass in a list of paths as a single parameter to the script.
        run: |
          .\buildtools\sign_files.ps1 -Filters AWS.Distro.OpenTelemetry.AutoInstrumentation.dll -Recurse -Path .\src\AWS.Distro.OpenTelemetry.AutoInstrumentation\bin\Release
          .\buildtools\sign_files.ps1 -Filters OpenTelemetry.Instrumentation.AWS.dll -Recurse -Path .\src\AWS.Distro.OpenTelemetry.AutoInstrumentation\bin\Release
          
      - name: Pack nugets
        run: >
          dotnet pack
          .\src\AWS.Distro.OpenTelemetry.AutoInstrumentation
          /p:Version=${{github.event.inputs.version}}
          --no-build
          -c Release
          -o .\Deployment\nuget-packages
      - name: Upload nugets to this GitHub Action run as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: Deployment/nuget-packages/

      - name: Assume nuget role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.NUGET_ACCESS_ROLE_ARN }}
          aws-region: ${{ env.AWS_SIGNING_KEY_REGION }}

      - name: Push packages to Nuget.org
        run: >
          $nugetKey = aws secretsmanager get-secret-value
          --secret-id ${{ secrets.NUGET_SECRETS_ID }}
          --region ${{ env.AWS_SIGNING_KEY_REGION }}
          --output text
          --query SecretString | ConvertFrom-Json
          nuget push
          .\Deployment\nuget-packages\*.nupkg
          -Source https://api.nuget.org/v3/index.json
          -ApiKey $nugetKey.Key