name: Test ADOT X-Ray UDP Exporter
on:
  workflow_call:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  udp-exporter-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v4
      - name: Set up .NET CLI
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Configure AWS credentials for Testing Tracing
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.XRAY_UDP_EXPORTER_TEST_ROLE }}
          aws-region: 'us-east-1'

      - name: Download and run X-Ray Daemon
        run: |
          mkdir xray-daemon
          cd xray-daemon
          wget https://s3.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-3.x.zip
          unzip aws-xray-daemon-linux-3.x.zip
          ./xray -o -n us-east-2 -f ./daemon-logs.log --log-level debug &

      - name: Create NuGet.Config with multiple sources
        working-directory: sample-applications/udp-exporter-test-app
        run: |
          cat > NuGet.Config << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <packageSources>
              <clear />
              <add key="local-udp-exporter" value="$GITHUB_WORKSPACE/exporters/AWS.Distro.OpenTelemetry.Exporter.Xray.Udp/bin/Release" />
              <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
            </packageSources>
          </configuration>
          EOF

          # Show the created config
          cat NuGet.Config

      - name: Build & Package the UDP exporter locally
        working-directory: exporters/AWS.Distro.OpenTelemetry.Exporter.Xray.Udp
        run: |
          dotnet pack -c Release

      - name: Run Sample App in Background
        working-directory: sample-applications/udp-exporter-test-app
        run: |
          # Install the locally built version of the UDP exporter
          dotnet add package AWS.Distro.OpenTelemetry.Exporter.Xray.Udp
          # Start validation app
          dotnet run &
          # Wait for validation app to initialize
          sleep 5

      - name: Call Sample App Endpoint
        id: call-endpoint
        run: |
          echo "traceId=$(curl localhost:8080/test | tr -d '\n')" >> $GITHUB_OUTPUT
      - name: Check if traces are successfully sent to AWS X-Ray
        run: |
          sleep 20
          # # Print Daemon Logs for debugging
          # cat xray-daemon/daemon-logs.log
          traceId=${{ steps.call-endpoint.outputs.traceId }}
          numTracesFound=$(aws xray batch-get-traces --trace-ids $traceId --region us-east-2 | jq '.Traces' | jq length)
          if [[ numTracesFound -ne "1" ]]; then
            echo "TraceId $traceId not found in X-Ray."
            exit 1
          else
            echo "TraceId $traceId found in X-Ray."
          fi
